### ISSUE TITLE
Unable to install flake on NixOS unstable

### ISSUE THREAD

**Issue by igorgue** [H3rmt/hyprswitch#41]
```
warning: Git tree '/etc/nixos' is dirty
building the system configuration...
warning: Git tree '/etc/nixos' is dirty
error: builder for '/nix/store/mdjf98d27mgdd4in5wxkrrimdy9j1wdk-hyprswitch.drv' failed with exit code 101;
       last 10 log lines:
       > Caused by:
       >   process didn't exit successfully: `/build/source/target/release/build/libc-d11dafa8b1a729d3/build-script-build` (exit status: 101)
       >   --- stdout
       >   cargo:rerun-if-changed=build.rs
       >
       >   --- stderr
       >   thread 'main' panicked at /build/cargo-vendor-dir/libc-0.2.153/build.rs:206:9:
       >   failed to run rustc:
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/mdjf98d27mgdd4in5wxkrrimdy9j1wdk-hyprswitch.drv'.
error: 1 dependencies of derivation '/nix/store/q0qq8gmgmb32nm17qkkfmqz6mab0rl3d-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d3hmp7nnjkhfyysixscbihcbfzfzz000-nixos-system-igorlaptop-24.11.20240629.2741b4b.drv' failed to build
```

Sounds like it's related to a Rust upgrade cause it's on libc.

**Comment by H3rmt** [comment]
What is the output of `nix log /nix/store/mdjf98d27mgdd4in5wxkrrimdy9j1wdk-hyprswitch.drv`?

**Comment by igorgue** [comment]
```
/etc/nixos (main*) # vi configuration.nix                                                                                                                                         root@igorlaptop
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/etc/nixos (main*) # wqawqal;                                                                                                                                                     root@igorlaptop
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/etc/nixos (main*) # :wqa                                                                                                                                                   130 ↵ root@igorlaptop
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/etc/nixos (main*) # ls                                                                                                                                                     130 ↵ root@igorlaptop
configuration.nix  flake.lock  flake.nix  hardware-configuration.nix  scripts
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/etc/nixos (main*) # u                                                                                                                                                            root@igorlaptop
unpacking channels...
warning: Git tree '/etc/nixos' is dirty
warning: Git tree '/etc/nixos' is dirty
building the system configuration...
warning: Git tree '/etc/nixos' is dirty
stopping the following units: accounts-daemon.service
activating the configuration...
setting up /etc...
reloading user units for igor...
restarting sysinit-reactivation.target
yw9-gcc-wrapper-13.2.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/kvlhk0gpm2iz1asbw1xjac2ch0r8kyw9-gcc-wrapper-13.2.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/kvlhk0gpm2iz1asbw1xjac2ch0r8kyw9-gcc-wrapper-13.2.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/kvlhk0gpm2iz1asbw1xjac2ch0r8kyw9-gcc-wrapper-13.2.0/bin/cc HOST_CXX=/nix/store/kvlhk0gpm2iz1asbw1xjac2ch0r8kyw9-gcc-wrapper-13.2.0/bin/c++ cargo build -j 16 --target x86_64-unknown-linux-gnu --frozen --profile release
   Compiling serde v1.0.197
   Compiling hashbrown v0.14.3
   Compiling equivalent v1.0.1
   Compiling winnow v0.5.40
   Compiling target-lexicon v0.12.14
   Compiling smallvec v1.13.1
   Compiling version-compare v0.1.1
   Compiling pkg-config v0.3.30
   Compiling heck v0.4.1
   Compiling proc-macro2 v1.0.78
   Compiling libc v0.2.153
   Compiling unicode-ident v1.0.12
   Compiling autocfg v1.1.0
   Compiling pin-project-lite v0.2.13
   Compiling memchr v2.7.1
   Compiling heck v0.5.0
   Compiling futures-core v0.3.30
   Compiling futures-task v0.3.30
   Compiling thiserror v1.0.57
   Compiling pin-utils v0.1.0
   Compiling futures-channel v0.3.30
   Compiling bitflags v2.4.2
   Compiling semver v1.0.22
   Compiling gio v0.19.4
   Compiling cfg-if v1.0.0
   Compiling futures-io v0.3.30
   Compiling parking_lot_core v0.9.9
   Compiling slab v0.4.9
   Compiling lock_api v0.4.11
   Compiling memoffset v0.9.0
   Compiling num-traits v0.2.19
error: failed to run custom build command for `libc v0.2.153`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/libc-d11dafa8b1a729d3/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at /build/cargo-vendor-dir/libc-0.2.153/build.rs:206:9:
  failed to run rustc: 
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by igorgue** [comment]
I'm not sure how to run the compile with the flag though, my config I'd say what's odd is I use `NIX_LD`, other than that this is the only flake I have installed.
